# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- UpdateToAngular13

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
  displayName: 'Install Angular CLI'

- script: |
    npm run install-with-legacy
  displayName: 'Install NPM packages'

############################
# Shared Library Build
############################

- script: |
    npm run sharedlib:build
  displayName: 'Build Shared Library'

############################
# Public Inspection Report Builds
############################

- script: |
    npm run report:build:staging
  displayName: 'Build Public Inspection Report - Staging'

- script: |
    npm run report:build:prod
  displayName: 'Build Public Inspection Report - Prod'

############################
# Internal Inspection Report Builds
############################

- script: |
    npm run report-internal:build:staging
  displayName: 'Build Internal Inspection Report - Staging'

- script: |
    npm run report-internal:build:prod
  displayName: 'Build Internal Inspection Report - Prod'

############################
# MyCar Builds
############################

- script: |
    npm run mycar:build:staging
  displayName: 'Build MyCar Membership Portal - Staging'

- script: |
    npm run mycar:build:prod
  displayName: 'Build MyCar Membership Portal - Prod'

############################
# Save Artifacts
############################

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: 'dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'murphy-automotive-apps'
